//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoom
    {
        public ChatRoom()
        {
            this.ChatMessages = new HashSet<ChatMessage>();
        }
    
        public int Id { get; set; }
        public int ParticipantAId { get; set; }
        public int ParticipantBId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<ChatMessage> ChatMessages { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual Participant Participant1 { get; set; }
    }
}
