//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Participant()
        {
            this.ChatMessages = new HashSet<ChatMessage>();
            this.ChatRooms = new HashSet<ChatRoom>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<ChatMessage> ChatMessages { get; set; }
        public virtual ICollection<ChatRoom> ChatRooms { get; set; }
    }
}
